services:
  postgres:
    image: postgres:16
    container_name: postgres1
    environment:
      POSTGRES_DB: futurestackhealth
      POSTGRES_USER: futurestackhealth
      POSTGRES_PASSWORD: futurestackhealth
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futurestackhealth -d futurestackhealth"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
